// "use client";
// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
// import "./globals.css";
// import { usePathname } from "next/navigation";
// import { AdminHeader } from "@/components/AdminHeader";
// import { AdminSidebar } from "@/components/AdminSidebar";

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   const pathname = usePathname();
//   const isHome = pathname.startsWith("/sign-in");
//   const isStudio = pathname.startsWith("/studio");
//   const studioAndSignIn = !isHome && !isStudio

//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <div className="min-h-screen">
//           {studioAndSignIn && <AdminHeader />}
//           <div className="flex">
//              {studioAndSignIn && <AdminSidebar />}
//             <main className="flex-1 bg-muted/40">

//         {children}
//         </main>
//           </div>
//         </div>
//       </body>
//     </html>
//   );
// }
// src\app\layout.tsx
"use client"
import "./globals.css";
import { usePathname } from "next/navigation";
import { AdminHeader } from "@/components/AdminHeader";
import { AdminSidebar } from "@/components/AdminSidebar";


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  const pathname = usePathname();

  const isHome = pathname.startsWith("/sign-in");
  const isStudio = pathname.startsWith("/studio");
  
  const studioAndSignIn = !isHome && !isStudio

  return (
    <html lang="en">
      <body>
        <div className="min-h-screen">
          {studioAndSignIn && <AdminHeader />}
          <div className="flex">
         
            {studioAndSignIn && <AdminSidebar />}
            <main className="flex-1 bg-muted/40">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}